version: "3.9"

services:
  keydb:
    image: eqalpha/keydb:latest
    restart: unless-stopped
    command: keydb-server /etc/keydb/redis.conf --server-threads 4
    volumes:
      - redis:/data
    ports:
      - "${REDIS_PORT:-6379}:6379"

  # scylla:
  #   image: scylladb/scylla:5.2
  #   restart: unless-stopped
  #   command: "--smp 1 --memory 1536M --overprovisioned 1"
  #   volumes:
  #     - database:/var/lib/scylla
  #   ports:
  #     - "${DB_PORT:-9042}:9042"
  
  minio:
    image: minio/minio:latest
    command: server /data
    volumes:
      - "data:/data"
    environment:
      - "MINIO_ROOT_USER=${S3_ACCESS_KEY_ID}"
      - "MINIO_ROOT_PASSWORD=${S3_ACCESS_KEY_SECRET}"
    ports:
      - "${MINIO_PORT:-9000}:9000"

  meilisearch:
    image: getmeili/meilisearch:v1.5
    environment:
      - http_proxy
      - https_proxy
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-masterKey}
      - MEILI_NO_ANALYTICS=${MEILI_NO_ANALYTICS:-true}
      - MEILI_ENV=${MEILI_ENV:-development}
      - MEILI_LOG_LEVEL
    ports:
      - ${MEILI_PORT:-7700}:7700
    volumes:
      - meili:/meili_data
    restart: unless-stopped

volumes:
  redis:
  # database:
  data:
  meili: